#!/usr/bin/env python3

import shutil
import sys
import glob
import subprocess
import os

if os.path.isdir('./dist'):
    shutil.rmtree('./dist')
subprocess.check_call([sys.executable, '-m', 'pip',
                      'uninstall', '-y', 'fmdpy'])
subprocess.check_call([sys.executable, './scripts/build.py'])
subprocess.check_call([sys.executable, '-m', 'pip', 'install',
                      glob.glob('./dist/fmdpy-*.whl')[0]])
